paths:
  converted_audio: audio_converted.wav
  fase2_filtered: fase2_filtered.json
phase0:
  block_duration: 30m
  max_speakers: 2
  min_speakers: 2
  residual_threshold: 5
  sample_duration: 60.0
phase2:
  last_parameters:
    drop_speakers: []
    merge_speakers: {}
    min_duration: 0.25
    min_pause: 2.0
    rename_speakers: {}
    timestamp: '2026-01-29 11:32:17'
project:
  created: '2026-01-29'
  name: PBC017_from20_A
